development:
  adapter: postgresql
  encoding: unicode
  database: monit_db
  pool: 5
  username: monitadmin
  password: 0ct0pus
  host: 127.0.0.1

production:
  adapter: postgresql
  encoding: unicode
  database: monitdb_production
  pool: 5
  username: monitadmin
  password: 0ct0pus
  host: 127.0.0.1